config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'visitors#home'

  resource :dashboard

  resources :emails, only: [:show, :new, :create] do
    collection do
      get :inbox
      get :sent
    end
  end

  scope '/admin' do
    resources :users
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    return unless user.present?
    can :manage,  Email, user_id: user.id
    can %i[inbox show], Email, mailboxes: { user_id: user.id }
    can :manage, User if user.admin?
  end
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :user
  has_many :mailboxes, dependent: :destroy
  has_many :users, through: :mailboxes

  before_validation :fill_user_email

  validates :to, :user, :subject, :body, presence: true

  after_commit :send_mailgun, on: :create

  scope :authored, (->(user) { where(author: user) })
  scope :recieved, (->(user) { joins(:mailboxes).where('mailboxes.user_id = ?', user.id) })

  attr_accessor :to_users

  def to_hash
    { id:      id,
      from:    author_email,
      to:      to,
      cc:      cc,
      bcc:     bcc,
      subject: subject,
      body:    body }
  end

  def author_email
    author.email
  end

  private

  def send_mailgun
    MailgunWorker.execute(id)
  end

  def fill_user_email
    return unless to_users.present?
    self.to = User.where(id: to_users).map(&:email)
  end
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
  belongs_to :user
  belongs_to :email
end

app/models/regular_user.rb
class RegularUser < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  self.inheritance_column = 'class_name'

  before_validation :create_password, on: :create

  has_many :mailboxes, dependent: :destroy
  has_many :emails, through: :mailboxes, dependent: :destroy
  has_many :authored_emails, class_name: 'Email', dependent: :destroy

  def username
    email.split('@').first
  end

  def admin?
    class_name == 'AdminUser'
  end

  private

  def create_password
    self.password = SecureRandom.hex if password.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render json: { success: false, status: 403, message: 'Not Permitted for this action' } }
      format.xml  { render xml: '...', status: 403, message: exception.message }
      format.html { redirect_to root_path, alert: exception.message }
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users -= [current_user]
  end

  def create
    if @user.save
      flash[:success] = 'Created Successfully'
      redirect_to users_path
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  def update
    if @user.save
      flash[:success] = 'Updated Successfully'
      redirect_to users_path
    else
      flash.now[:error] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = 'Deleted Successfully'
    else
      flash.now[:error] = @user.errors.full_messages
    end
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :name)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  layout 'visitors'

  def home
    redirect_to current_user.present? ? dashboard_path : new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/dashboards/show.html.haml
.right_col{:role => "main", :style => "min-height: 100%;"}
  %div
    .page-title
      .title_left
        %h3 Dashboard
      .title_right
        .col-md-5.col-sm-5.col-xs-12.form-group.pull-right.top_search
          .input-group
            %input.form-control{:placeholder => "Search for...", :type => "text"}/
            %span.input-group-btn
              %button.btn.btn-default{:type => "button"} Go!
    .clearfix
    .row
      .col-md-12.col-sm-12.col-xs-12
        .x_panel
          .x_title
            %h2 Alkimii
            %ul.nav.navbar-right.panel_toolbox
              %li
                %a.collapse-link
                  %i.fa.fa-chevron-up
              -# %li.dropdown
              -#   %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              -#     %i.fa.fa-wrench
              -#   %ul.dropdown-menu{:role => "menu"}
              -#     %li
              -#       %a{:href => "#"} Settings 1
              -#     %li
              -#       %a{:href => "#"} Settings 2
              %li
                %a.close-link
                  %i.fa.fa-close
            .clearfix
          .x_content
            Alkimii Mailer

app/views/layouts/_footer.html.haml
%footer
  .pull-right
    Guppies
    %a{:href => "#"} Fady Naffa
  .clearfix

app/views/layouts/_left_sidebar.html.haml
/ sidebar menu

.col-md-3.left_col
  .left_col.scroll-view
    .profile.clearfix
      .profile_pic
        %img.img-circle.profile_img{:alt => "...", :src => "/images/profile.png"}/
      .profile_info
        %span Welcome,
        %h2= current_user.email.split('@').first
      .clearfix
    / /menu profile quick info
    %br/


    #sidebar-menu.main_menu_side.hidden-print.main_menu
      .menu_section
        %ul.nav.side-menu
          %li
            = link_to dashboard_path do
              %i.fa.fa-home
              Home
          %li
            %a
              %i.fa.fa-envelope
              Mail
              %span.fa.fa-chevron-down
            %ul.nav.child_menu
              %li
                = link_to inbox_emails_path do
                  %i.fa.fa-inbox
                  Inbox
              %li
                = link_to sent_emails_path do
                  %i.fa.fa-send
                  Sent
              %li
                = link_to new_email_path do
                  %i.fa.fa-file-text
                  Compose
          - if can? :manage, User
            %li
              %a
                %i.fa.fa-user
                Users
                %span.fa.fa-chevron-down
              %ul.nav.child_menu
                %li
                  = link_to users_path do
                    %i.fa.fa-inbox
                    List users
                %li
                  = link_to new_user_path do
                    %i.fa.fa-plus
                    Add User

      / /menu footer buttons
      .sidebar-footer.hidden-small
        %a{"data-original-title" => "Settings", "data-placement" => "top", "data-toggle" => "tooltip", :title => ""}
          %span.glyphicon.glyphicon-cog{"aria-hidden" => "true"}
        %a{"data-original-title" => "FullScreen", "data-placement" => "top", "data-toggle" => "tooltip", :title => ""}
          %span.glyphicon.glyphicon-fullscreen{"aria-hidden" => "true"}
        %a{"data-original-title" => "Lock", "data-placement" => "top", "data-toggle" => "tooltip", :title => ""}
          %span.glyphicon.glyphicon-eye-close{"aria-hidden" => "true"}

        = link_to destroy_user_session_path, method: 'delete', "data-original-title" => "Logout", "data-placement" => "top", "data-toggle" => "tooltip", :title => "" do
          %span.glyphicon.glyphicon-off{"aria-hidden" => "true"}

app/views/layouts/_message.html.haml
%div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
  %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
  = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = render partial: '/layouts/message', locals: { msg: msg, name: name }
  - if msg.is_a?(Array)
    - msg.each do |m|
      = render partial: '/layouts/message', locals: { msg: m, name: name }

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
= render partial: '/layouts/nav_links_for_auth'

app/views/layouts/_top_navigation.html.haml
/ top navigation
.top_nav
  .nav_menu
    %nav
      .nav.toggle
        %a#menu_toggle
          %i.fa.fa-bars
      %ul.nav.navbar-nav.navbar-right
        %li
          %a.user-profile.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "javascript:;"}
            %img{:alt => "", :src => "/images/profile.png"}>/
            = current_user.email.split('@').first
            %span.fa.fa-angle-down
          %ul.dropdown-menu.dropdown-usermenu.pull-right
            %li
            -#   %a{:href => "javascript:;"} Profile
            -# %li
            -#   %a{:href => "javascript:;"}
            -#     %span.badge.bg-red.pull-right 50%
            -#     %span Settings
            -# %li
            -#   %a{:href => "javascript:;"} Help
            -# %li
            -#   %a{:href => "login.html"}
            -#     %i.fa.fa-sign-out.pull-right
            -#     Log Out
        %li.dropdown{:role => "presentation"}
          %a.dropdown-toggle.info-number{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "javascript:;"}
            %i.fa.fa-envelope-o
            %span.badge.bg-green 1
          %ul#menu1.dropdown-menu.list-unstyled.msg_list{:role => "menu"}
            %li
              %a
                %span.image
                  -# %img{:alt => "Profile Image", :src => "images/img.jpg"}/
                %span
                  %span Coming Soon
                  %span.time 3 mins ago
                %span.message
                  coming soon

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Alkimii Mailer'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Alkimii Mailer'}"}
    = stylesheet_link_tag 'application'
    = csrf_meta_tags
  %body{:class => [controller.controller_name, controller.action_name, @class, 'nav-md']}
    .container.body
      .main_container
        = render 'layouts/messages'
        - if current_user.present?
          = render partial: '/layouts/left_sidebar'
          = render partial: '/layouts/top_navigation'
        = yield
      = render partial: '/layouts/footer' if current_user.present?
    = javascript_include_tag 'application'
    = yield :javascript_includes

app/views/layouts/visitors.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Alkimii Mailer'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Alkimii Mailer'}"}
    = stylesheet_link_tag 'application'
    = csrf_meta_tags
  %body{:class => [controller.controller_name, controller.action_name, @class, 'nav-md']}
    .container.body
      .main_container
        = yield
    = javascript_include_tag 'application'

app/views/users/_form.html.haml
= form_for(@user, html: { class: 'form form-horizontal' }) do |f|
  .form-group
    = f.label :name, 'Name', class: 'control-label col-xs-2'
    .col-xs-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'Email', class: 'control-label col-xs-2'
    .col-xs-10
      = f.email_field :email, class: 'form-control'

  .form-group
    .col-xs-3.pull-right
      = f.submit 'Submit', class: 'btn btn-sm btn-success btn-block pull-right'

app/views/users/edit.html.haml
.right_col{:role => "main", :style => "min-height: 100%;"}
  %div
    .page-title
      .title_left
        %h3 Users
    .clearfix
    .row
      .col-md-12.col-sm-12.col-xs-12
        .x_panel
          .x_content
            = render partial: 'form'

app/views/users/index.html.haml
.right_col{:role => "main", :style => "min-height: 100%;"}
  %div
    .page-title
      .title_left
        %h3 Dashboard
      .title_right
        .col-md-5.col-sm-5.col-xs-12.form-group.pull-right.top_search
          .input-group
            %input.form-control{:placeholder => "Search for...", :type => "text"}/
            %span.input-group-btn
              %button.btn.btn-default{:type => "button"} Go!
    .clearfix
    .row
      .col-md-12.col-sm-12.col-xs-12
        .x_panel
          .x_content
            %table.table.table-condensed.table-striped.datatable
              %thead
                %tr
                  %th User ID
                  %th Email
                  %th Created at
                  %th Last Sign in
                  %th Edit
                  %th Delete
              %tbody
                - @users.each do |user|
                  %tr
                    %td= user.id
                    %td= user.email
                    %td= user.created_at
                    %td= user.last_sign_in_at
                    %td= link_to 'Edit', edit_user_path(user)
                    %td= link_to 'Delete', user_path(user), method: :delete, "data-confirm": 'Are You Sure?'

app/views/users/new.html.haml
.right_col{:role => "main", :style => "min-height: 100%;"}
  %div
    .page-title
      .title_left
        %h3 Users
    .clearfix
    .row
      .col-md-12.col-sm-12.col-xs-12
        .x_panel
          .x_content
            = render partial: 'form'